twm files

diff --git a/src/share/xde/twm/start b/src/share/xde/twm/start
--- a/src/share/xde/twm/start
+++ b/src/share/xde/twm/start
@@ -1,65 +1,57 @@
 #!/bin/bash
 
-here="$(dirname $0)"
-case "$here" in /*) ;; *) here=`(cd "$here"; pwd)` ;; esac
+prog=$0
+here=$(echo $prog|sed 's,/[^/]*$,,')
+here=`(cd "$here"; pwd)`
+prog=$(echo "$prog"|sed 's,^.*/,,')
 
-name=twm
-
-[ -n "$XDG_CONFIG_HOME" ] || XDG_CONFIG_HOME="$HOME/.config"
-[ -n "$XDG_DATA_HOME"   ] || XDG_DATA_HOME="$HOME/.local/share"
-[ -n "$XDG_CONFIG_DIRS" ] || XDG_CONFIG_DIRS="/etc/xdg"
-[ -n "$XDG_DATA_DIRS"   ] || XDG_DATA_DIRS="/usr/local/share:/usr/share"
-
-prog=${1:-${TWM_TYPE:-$name}}
-if [ ! -x "`which $prog 2>/dev/null`" ]; then
-    echo "ERROR: cannot find usable $prog program" >&2
-    exit 1
+export TWM_TYPE=${1:-${TWM_TYPE:-twm}}
+if [ ! -x "`which $TWM_TYPE 2>/dev/null`" ]; then
+    echo "ERROR: cannot find usable twm program" >&2
+    exit 1;
 fi
-vers=${2:-${TWM_VERSION}}
-if [ -z "$vers" ]; then
-    vers='1.0.8'
+if [ -z "$TWM_VERSION" ]; then
+    TWM_VERSION='1.0.8'
 fi
-sdir="${TWM_CONFIG_SDIR:-/usr/share/$prog}"
-if [ -z "$XDG_USE_XDG_HOME" ]; then
-    path="${TWM_CONFIG_HOME:-${HOME:-~}/.$prog}"
-else
-    path="${TWM_CONFIG_HOME:-${XDG_CONFIG_HOME:-${HOME:-~}/.config}/$prog}"
-fi
-export TWM_TYPE="$prog"
-export TWM_VERSION="$vers"
-export TWM_CONFIG_HOME="$path"
-export TWM_CONFIG_SDIR="$sdir"
-export TWM_CONFIG_EDIR="$here"
+export TWM_VERSION=${2:-$TWM_VERSION}
+export TWM_CONFIG_HOME=${TWM_CONFIG_HOME:-${HOME:-~}/.$TWM_TYPE}
+export TWM_CONFIG_SDIR=${TWM_CONFIG_SDIR:-/usr/share/$TWM_TYPE}
 
-xprop -root -format _NET_WM_PID 32c -set _NET_WM_PID $$
-xprop -root -format _NET_WM_NAME 8u -set _NET_WM_NAME "$prog $vers"
-
-if [ -z "$XDE_NOEXEC" ]; then
-    export TWM_TYPE="$prog"
-    export TWM_VERSION="$vers"
-    export TWM_CONFIG_HOME="$path"
-    export TWM_CONFIG_SDIR="$sdir"
-    if true; then
-	if [ -x "$sdir/config" ]; then
-	    "$sdir/config" $prog $vers
-	elif [ -x "$path/config" ]; then
-	    "$path/config" $prog $vers
-	else
-	    echo "WARNING: cannot find config program: winging it" >&2
-	    exec $prog -f "$path/rc"
-	fi
-	exec $prog -f "$path/rc"
+[ -d "$TWM_CONFIG_HOME" ] || mkdir -p "$TWM_CONFIG_HOME"
+if [ -s "$TWM_CONFIG_SDIR/version" ]; then
+    if [ ! -s "$TWM_CONFIG_HOME/version" -o ! diff "$TWM_CONFIG_SDIR/version" "$TWM_CONFIG_HOME/version" ] ; then
+	for file in apps defaults keys menu stylemenu version winmenu; do
+	    if [ ! -f "$TWM_CONFIG_SDIR/$file" -o ! diff "$TWM_CONFIG_SDIR/$file" "$TWM_CONFIG_HOME/$file" ] ; then
+		[ ! -f "$TWM_CONFIG_HOME/$file" ] || /bin/mv -f "$TWM_CONFIG_HOME/$file" "$TWM_CONFIG_HOME/$file.bak"
+		/bin/cp -f "$TWM_CONFIG_SDIR/$file" "$TWM_CONFIG_HOME/$file"
     fi
-else
-    echo "export TWM_TYPE=\"$prog\"" >&2
-    echo "export TWM_VERSION=\"$vers\"" >&2
-    echo "export TWM_CONFIG_HOME=\"$path\"" >&2
-    echo "export TWM_CONFIG_SDIR=\"$sdir\"" >&2
-    if true; then
-	echo "exec $prog -f \"$path/rc\"" >&2
+	done
     fi
 fi
 
-exit 1
+if [ -x "`which xde-menugen 2>/dev/null`" ]; then
+    xde-menugen --format $TWM_TYPE >"$TWM_CONFIG_HOME/menu"
+fi
 
-# vim: set ft=sh sw=4:
+config="$here/config"
+[ -x "$config" ] || config="$TWM_CONFIG_HOME/config"
+[ -x "$config" ] || config="$TWM_CONFIG_SDIR/config"
+[ -x "$config" ] && $config
+
+getstyles="$here/getstyles"
+[ -x "$getstyles" ] || getstyles="$TWM_CONFIG_HOME/getstyles"
+[ -x "$getstyles" ] || getstyles="$TWM_CONFIG_SDIR/getstyles"
+[ -x "$getstyles" ] && $getstyles
+
+export TWM_RCFILE="${HOME:-~}/.${TWM_TYPE}rc"
+
+if [ -L "$TWM_RCFILE" ]; then
+    /bin/rm -f "$TWM_RCFILE"
+elif [ -s  "$TWM_RCFILE" ]; then
+    /bin/mv -f "${TWM_RCFILE}" "${TWM_RCFILE}.bak"
+fi
+/bin/ln -sf "$TWM_CONFIG_HOME/rc" "$TWM_RCFILE"
+
+exec $TWM_TYPE -f "$TWM_CONFIG_HOME/rc"
+
+# vim: sw=4
